# Macro Placement for OpenROAD-flow-scripts
# Generated by partcl-macro-place-challenge
#
# Two-pass runtime matching: groups ODB macros by sram block prefix,
# then matches to .plc macro_mem[K] by linear index within each group.

# Placement data: group_prefix -> flat_index -> {x y orient plc_name}
set _gpd [dict create]

# Pass 1: Collect all block instances, grouped by sram prefix
# ODB name pattern: PREFIX.genblk1_G__i_ram.macro_mem_M
# We extract PREFIX (everything before .genblk1_), G, and M.
set _odb_groups [dict create]
set block [ord::get_db_block]
foreach inst [$block getInsts] {
    if {[$inst isBlock]} {
        set name [$inst getName]
        # Match the genblk pattern
        if {[regexp {^(.+)\.genblk1_(\d+)__i_ram\.macro_mem_(\d+)$} $name -> prefix genblk_idx mem_idx]} {
            dict lappend _odb_groups $prefix [list $genblk_idx $mem_idx $name]
        }
    }
}

# Pass 2: For each group, sort by (genblk_idx, mem_idx) to get linear ordering,
# then match to our .plc flat indices.
set _placed 0
set _unmatched_odb [list]
set _unmatched_plc [list]

dict for {prefix entries} $_odb_groups {
    # Sort entries by genblk_idx then mem_idx (both numeric)
    set sorted_entries [lsort -command {apply {{a b} {
        lassign $a ga ma
        lassign $b gb mb
        set ga [expr {int($ga)}]; set ma [expr {int($ma)}]
        set gb [expr {int($gb)}]; set mb [expr {int($mb)}]
        if {$ga != $gb} { return [expr {$ga - $gb}] }
        return [expr {$ma - $mb}]
    }}} $entries]

    # Assign linear index K=0,1,2,...
    set k 0
    foreach entry $sorted_entries {
        lassign $entry genblk_idx mem_idx odb_name
        if {[dict exists $_gpd $prefix] && [dict exists [dict get $_gpd $prefix] $k]} {
            lassign [dict get [dict get $_gpd $prefix] $k] x y orient plc_name
            place_macro -macro_name [list $odb_name] -location [list $x $y] -orientation $orient
            incr _placed
        } else {
            lappend _unmatched_odb "$odb_name (group=$prefix, k=$k)"
        }
        incr k
    }
}

puts "Placed $_placed macros (expected 0)"
if {$_placed != 0} {
    puts "WARNING: Expected 0 macros but placed $_placed"
    if {[llength $_unmatched_odb] > 0} {
        puts "Unmatched ODB instances:"
        foreach u $_unmatched_odb { puts "  $u" }
    }
}
