# Macro Placement for OpenROAD-flow-scripts
# Generated by partcl-macro-place-challenge
#
# Runtime matching strategy:
# 1) Direct hierarchical-name matching for explicit .plc macro names
# 2) Group/index matching for macro_mem[K] style names

# Direct placement data
set _dpd [dict create]
set _direct_expected [list]

# Placement data: group_prefix -> flat_index -> {x y orient plc_name}
set _gpd [dict create]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__data_sram} 0 [list 1043.354980 1297.199951 N {i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__data_sram} 1 [list 12.070000 1441.400024 N {i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__data_sram} 2 [list 640.240051 1300.000000 N {i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__data_sram} 3 [list 247.630005 1299.800049 N {i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__data_sram} 4 [list 721.370056 1300.000000 N {i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__data_sram} 5 [list 486.079987 1451.199951 N {i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__data_sram} 6 [list 885.460022 1293.000000 N {i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__data_sram} 7 [list 327.239990 1299.800049 N {i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__tag_sram} 0 [list 12.070000 328.200012 N {i_cache_subsystem/i_icache/sram_block[0].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__tag_sram} 1 [list 12.070000 481.000000 N {i_cache_subsystem/i_icache/sram_block[0].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_0__tag_sram} 2 [list 12.070000 168.600006 S {i_cache_subsystem/i_icache/sram_block[0].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__data_sram} 0 [list 1122.954956 1451.199951 N {i_cache_subsystem/i_icache/sram_block[1].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__data_sram} 1 [list 88.669998 1448.199951 S {i_cache_subsystem/i_icache/sram_block[1].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__data_sram} 2 [list 565.570007 1451.199951 N {i_cache_subsystem/i_icache/sram_block[1].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__data_sram} 3 [list 168.470001 1452.599976 S {i_cache_subsystem/i_icache/sram_block[1].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__data_sram} 4 [list 807.559998 1451.199951 N {i_cache_subsystem/i_icache/sram_block[1].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__data_sram} 5 [list 407.609985 1444.199951 N {i_cache_subsystem/i_icache/sram_block[1].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__data_sram} 6 [list 885.460022 1451.199951 N {i_cache_subsystem/i_icache/sram_block[1].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__data_sram} 7 [list 248.269989 1452.599976 N {i_cache_subsystem/i_icache/sram_block[1].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__tag_sram} 0 [list 88.100006 174.399994 N {i_cache_subsystem/i_icache/sram_block[1].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__tag_sram} 1 [list 88.100006 488.000000 N {i_cache_subsystem/i_icache/sram_block[1].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_1__tag_sram} 2 [list 12.670002 13.400002 N {i_cache_subsystem/i_icache/sram_block[1].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__data_sram} 0 [list 1043.354980 1451.199951 N {i_cache_subsystem/i_icache/sram_block[2].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__data_sram} 1 [list 86.960007 1286.000000 N {i_cache_subsystem/i_icache/sram_block[2].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__data_sram} 2 [list 644.800049 1451.199951 N {i_cache_subsystem/i_icache/sram_block[2].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__data_sram} 3 [list 165.239990 1299.800049 N {i_cache_subsystem/i_icache/sram_block[2].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__data_sram} 4 [list 724.030029 1451.199951 N {i_cache_subsystem/i_icache/sram_block[2].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__data_sram} 5 [list 483.610016 1293.000000 N {i_cache_subsystem/i_icache/sram_block[2].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__data_sram} 6 [list 963.740051 1451.199951 N {i_cache_subsystem/i_icache/sram_block[2].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__data_sram} 7 [list 304.440002 1147.199951 N {i_cache_subsystem/i_icache/sram_block[2].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__tag_sram} 0 [list 168.209991 328.200012 N {i_cache_subsystem/i_icache/sram_block[2].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__tag_sram} 1 [list 88.100006 328.200012 N {i_cache_subsystem/i_icache/sram_block[2].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_2__tag_sram} 2 [list 90.949997 13.400002 N {i_cache_subsystem/i_icache/sram_block[2].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__data_sram} 0 [list 1122.954956 1297.199951 N {i_cache_subsystem/i_icache/sram_block[3].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__data_sram} 1 [list 12.070000 1286.000000 N {i_cache_subsystem/i_icache/sram_block[3].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__data_sram} 2 [list 562.150024 1293.000000 N {i_cache_subsystem/i_icache/sram_block[3].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__data_sram} 3 [list 226.160004 1147.199951 N {i_cache_subsystem/i_icache/sram_block[3].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__data_sram} 4 [list 806.800049 1293.000000 N {i_cache_subsystem/i_icache/sram_block[3].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__data_sram} 5 [list 405.899994 1283.199951 N {i_cache_subsystem/i_icache/sram_block[3].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__data_sram} 6 [list 963.740051 1293.000000 N {i_cache_subsystem/i_icache/sram_block[3].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__data_sram} 7 [list 329.329987 1452.599976 N {i_cache_subsystem/i_icache/sram_block[3].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__tag_sram} 0 [list 167.259995 174.399994 N {i_cache_subsystem/i_icache/sram_block[3].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__tag_sram} 1 [list 35.469997 634.799988 S {i_cache_subsystem/i_icache/sram_block[3].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_icache.sram_block_3__tag_sram} 2 [list 169.539993 13.199997 N {i_cache_subsystem/i_icache/sram_block[3].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__data_sram} 0 [list 1277.244995 649.000000 N {i_cache_subsystem/i_nbdcache/sram_block[0].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__data_sram} 1 [list 864.370056 499.000000 N {i_cache_subsystem/i_nbdcache/sram_block[0].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__data_sram} 2 [list 901.230042 816.799988 N {i_cache_subsystem/i_nbdcache/sram_block[0].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__data_sram} 3 [list 1216.054932 821.000000 N {i_cache_subsystem/i_nbdcache/sram_block[0].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__data_sram} 4 [list 1198.954956 663.000000 N {i_cache_subsystem/i_nbdcache/sram_block[0].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__data_sram} 5 [list 954.809998 188.199997 N {i_cache_subsystem/i_nbdcache/sram_block[0].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__data_sram} 6 [list 747.020020 800.000000 S {i_cache_subsystem/i_nbdcache/sram_block[0].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__data_sram} 7 [list 1062.414917 987.800049 N {i_cache_subsystem/i_nbdcache/sram_block[0].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__tag_sram} 0 [list 323.130005 328.200012 S {i_cache_subsystem/i_nbdcache/sram_block[0].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__tag_sram} 1 [list 244.850006 168.600006 S {i_cache_subsystem/i_nbdcache/sram_block[0].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_0__tag_sram} 2 [list 719.590027 165.800003 N {i_cache_subsystem/i_nbdcache/sram_block[0].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__data_sram} 0 [list 1355.525024 649.000000 N {i_cache_subsystem/i_nbdcache/sram_block[1].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__data_sram} 1 [list 885.080017 654.599976 N {i_cache_subsystem/i_nbdcache/sram_block[1].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__data_sram} 2 [list 978.555054 816.799988 N {i_cache_subsystem/i_nbdcache/sram_block[1].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__data_sram} 3 [list 1217.954956 976.599976 N {i_cache_subsystem/i_nbdcache/sram_block[1].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__data_sram} 4 [list 1120.674927 654.599976 N {i_cache_subsystem/i_nbdcache/sram_block[1].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__data_sram} 5 [list 889.640015 343.600006 N {i_cache_subsystem/i_nbdcache/sram_block[1].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__data_sram} 6 [list 753.220032 994.800049 N {i_cache_subsystem/i_nbdcache/sram_block[1].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__data_sram} 7 [list 1138.154907 821.000000 N {i_cache_subsystem/i_nbdcache/sram_block[1].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__tag_sram} 0 [list 404.760010 328.200012 N {i_cache_subsystem/i_nbdcache/sram_block[1].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__tag_sram} 1 [list 404.760010 172.800003 N {i_cache_subsystem/i_nbdcache/sram_block[1].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_1__tag_sram} 2 [list 640.930054 172.800003 N {i_cache_subsystem/i_nbdcache/sram_block[1].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__data_sram} 0 [list 1285.784912 493.400024 N {i_cache_subsystem/i_nbdcache/sram_block[2].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__data_sram} 1 [list 942.270020 499.000000 N {i_cache_subsystem/i_nbdcache/sram_block[2].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__data_sram} 2 [list 829.980042 964.000000 N {i_cache_subsystem/i_nbdcache/sram_block[2].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__data_sram} 3 [list 1150.895020 1141.800049 N {i_cache_subsystem/i_nbdcache/sram_block[2].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__data_sram} 4 [list 1207.694946 506.000000 N {i_cache_subsystem/i_nbdcache/sram_block[2].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__data_sram} 5 [list 968.110046 343.600006 N {i_cache_subsystem/i_nbdcache/sram_block[2].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__data_sram} 6 [list 913.770020 1130.599976 N {i_cache_subsystem/i_nbdcache/sram_block[2].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__data_sram} 7 [list 1450.525024 821.000000 N {i_cache_subsystem/i_nbdcache/sram_block[2].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__tag_sram} 0 [list 567.210022 328.200012 N {i_cache_subsystem/i_nbdcache/sram_block[2].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__tag_sram} 1 [list 247.889984 13.199997 S {i_cache_subsystem/i_nbdcache/sram_block[2].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_2__tag_sram} 2 [list 717.880005 13.199997 N {i_cache_subsystem/i_nbdcache/sram_block[2].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__data_sram} 0 [list 1444.814941 513.000000 N {i_cache_subsystem/i_nbdcache/sram_block[3].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__data_sram} 1 [list 962.600037 654.599976 N {i_cache_subsystem/i_nbdcache/sram_block[3].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__data_sram} 2 [list 907.309998 972.400024 N {i_cache_subsystem/i_nbdcache/sram_block[3].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__data_sram} 3 [list 1140.635010 987.800049 N {i_cache_subsystem/i_nbdcache/sram_block[3].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__data_sram} 4 [list 1126.005005 343.600006 N {i_cache_subsystem/i_nbdcache/sram_block[3].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__data_sram} 5 [list 1033.094971 188.199997 N {i_cache_subsystem/i_nbdcache/sram_block[3].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__data_sram} 6 [list 835.870056 1123.599976 N {i_cache_subsystem/i_nbdcache/sram_block[3].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__data_sram} 7 [list 1451.474976 976.599976 N {i_cache_subsystem/i_nbdcache/sram_block[3].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__tag_sram} 0 [list 489.879974 333.799988 N {i_cache_subsystem/i_nbdcache/sram_block[3].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__tag_sram} 1 [list 403.809998 13.199997 N {i_cache_subsystem/i_nbdcache/sram_block[3].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_3__tag_sram} 2 [list 638.270020 13.199997 N {i_cache_subsystem/i_nbdcache/sram_block[3].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__data_sram} 0 [list 1364.824951 493.400024 N {i_cache_subsystem/i_nbdcache/sram_block[4].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__data_sram} 1 [list 729.920044 628.000000 N {i_cache_subsystem/i_nbdcache/sram_block[4].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__data_sram} 2 [list 984.635010 972.400024 N {i_cache_subsystem/i_nbdcache/sram_block[4].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__data_sram} 3 [list 1228.984985 1133.400024 N {i_cache_subsystem/i_nbdcache/sram_block[4].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__data_sram} 4 [list 1197.054932 195.200012 N {i_cache_subsystem/i_nbdcache/sram_block[4].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__data_sram} 5 [list 876.910034 188.199997 N {i_cache_subsystem/i_nbdcache/sram_block[4].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__data_sram} 6 [list 758.160034 1148.800049 N {i_cache_subsystem/i_nbdcache/sram_block[4].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__data_sram} 7 [list 1373.385010 976.599976 N {i_cache_subsystem/i_nbdcache/sram_block[4].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__tag_sram} 0 [list 438.649994 481.000000 N {i_cache_subsystem/i_nbdcache/sram_block[4].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__tag_sram} 1 [list 484.749969 172.800003 N {i_cache_subsystem/i_nbdcache/sram_block[4].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_4__tag_sram} 2 [list 875.390015 32.800003 N {i_cache_subsystem/i_nbdcache/sram_block[4].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__data_sram} 0 [list 1129.994995 499.000000 N {i_cache_subsystem/i_nbdcache/sram_block[5].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__data_sram} 1 [list 669.309998 482.400024 S {i_cache_subsystem/i_nbdcache/sram_block[5].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__data_sram} 2 [list 596.920044 972.400024 N {i_cache_subsystem/i_nbdcache/sram_block[5].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__data_sram} 3 [list 1072.114990 1141.800049 N {i_cache_subsystem/i_nbdcache/sram_block[5].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__data_sram} 4 [list 1204.474976 350.600006 N {i_cache_subsystem/i_nbdcache/sram_block[5].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__data_sram} 5 [list 799.080017 193.799988 S {i_cache_subsystem/i_nbdcache/sram_block[5].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__data_sram} 6 [list 679.570007 1148.800049 N {i_cache_subsystem/i_nbdcache/sram_block[5].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__data_sram} 7 [list 1371.864990 821.000000 N {i_cache_subsystem/i_nbdcache/sram_block[5].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__tag_sram} 0 [list 592.100037 482.400024 N {i_cache_subsystem/i_nbdcache/sram_block[5].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__tag_sram} 1 [list 482.089996 13.199997 N {i_cache_subsystem/i_nbdcache/sram_block[5].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_5__tag_sram} 2 [list 796.730042 32.800003 N {i_cache_subsystem/i_nbdcache/sram_block[5].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__data_sram} 0 [list 1040.944946 654.599976 N {i_cache_subsystem/i_nbdcache/sram_block[6].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__data_sram} 1 [list 807.559998 647.599976 N {i_cache_subsystem/i_nbdcache/sram_block[6].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__data_sram} 2 [list 668.550049 842.000000 S {i_cache_subsystem/i_nbdcache/sram_block[6].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__data_sram} 3 [list 1056.525024 816.799988 S {i_cache_subsystem/i_nbdcache/sram_block[6].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__data_sram} 4 [list 1047.784912 343.600006 S {i_cache_subsystem/i_nbdcache/sram_block[6].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__data_sram} 5 [list 724.410034 319.799988 S {i_cache_subsystem/i_nbdcache/sram_block[6].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__data_sram} 6 [list 823.900024 807.000000 N {i_cache_subsystem/i_nbdcache/sram_block[6].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__data_sram} 7 [list 1293.954956 821.000000 N {i_cache_subsystem/i_nbdcache/sram_block[6].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__tag_sram} 0 [list 246.179993 328.200012 S {i_cache_subsystem/i_nbdcache/sram_block[6].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__tag_sram} 1 [list 322.179993 168.600006 S {i_cache_subsystem/i_nbdcache/sram_block[6].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_6__tag_sram} 2 [list 563.030029 172.800003 N {i_cache_subsystem/i_nbdcache/sram_block[6].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__data_sram} 0 [list 1021.005066 499.000000 S {i_cache_subsystem/i_nbdcache/sram_block[7].data_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__data_sram} 1 [list 747.210022 471.000000 S {i_cache_subsystem/i_nbdcache/sram_block[7].data_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__data_sram} 2 [list 675.200012 994.800049 N {i_cache_subsystem/i_nbdcache/sram_block[7].data_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__data_sram} 3 [list 993.065002 1130.599976 N {i_cache_subsystem/i_nbdcache/sram_block[7].data_sram/macro_mem[3].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__data_sram} 4 [list 1116.505005 188.199997 N {i_cache_subsystem/i_nbdcache/sram_block[7].data_sram/macro_mem[4].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__data_sram} 5 [list 814.780029 350.600006 N {i_cache_subsystem/i_nbdcache/sram_block[7].data_sram/macro_mem[5].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__data_sram} 6 [list 600.910034 1127.800049 N {i_cache_subsystem/i_nbdcache/sram_block[7].data_sram/macro_mem[6].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__data_sram} 7 [list 1295.664917 976.599976 N {i_cache_subsystem/i_nbdcache/sram_block[7].data_sram/macro_mem[7].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__tag_sram} 0 [list 645.680054 328.200012 N {i_cache_subsystem/i_nbdcache/sram_block[7].tag_sram/macro_mem[0].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__tag_sram} 1 [list 325.980011 13.199997 S {i_cache_subsystem/i_nbdcache/sram_block[7].tag_sram/macro_mem[1].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.sram_block_7__tag_sram} 2 [list 560.180054 13.199997 N {i_cache_subsystem/i_nbdcache/sram_block[7].tag_sram/macro_mem[2].i_ram}]
dict set _gpd {i_cache_subsystem.i_nbdcache.valid_dirty_sram} 0 [list 515.720032 499.000000 N {i_cache_subsystem/i_nbdcache/valid_dirty_sram/macro_mem[0].i_ram}]

# Pass 1: Scan all block instances.
# - Apply direct-name placements first.
# - Collect genblk-style names for group/index matching.
set _odb_groups [dict create]
set _matched_direct [dict create]
set _matched_group [dict create]
set _placed 0
set _unmatched_odb [list]
set _unmatched_plc [list]

set block [ord::get_db_block]
foreach inst [$block getInsts] {
    if {![$inst isBlock]} {
        continue
    }

    set name [$inst getName]

    if {[dict exists $_dpd $name]} {
        lassign [dict get $_dpd $name] x y orient plc_name
        place_macro -macro_name [list $name] -location [list $x $y] -orientation $orient
        dict set _matched_direct $plc_name 1
        incr _placed
        continue
    }

    if {[regexp {^(.+)\.genblk1_(\d+)__i_ram\.macro_mem_(\d+)$} $name -> prefix genblk_idx mem_idx]} {
        dict lappend _odb_groups $prefix [list $genblk_idx $mem_idx $name]
        continue
    }

    lappend _unmatched_odb $name
}

# Pass 2: For each group, sort by (genblk_idx, mem_idx) to get linear ordering,
# then match to our .plc flat indices.
dict for {prefix entries} $_odb_groups {
    # Sort entries by genblk_idx then mem_idx (both numeric)
    set sorted_entries [lsort -command {apply {{a b} {
        lassign $a ga ma
        lassign $b gb mb
        set ga [expr {int($ga)}]; set ma [expr {int($ma)}]
        set gb [expr {int($gb)}]; set mb [expr {int($mb)}]
        if {$ga != $gb} { return [expr {$ga - $gb}] }
        return [expr {$ma - $mb}]
    }}} $entries]

    # Assign linear index K=0,1,2,...
    set k 0
    foreach entry $sorted_entries {
        lassign $entry genblk_idx mem_idx odb_name
        if {[dict exists $_gpd $prefix] && [dict exists [dict get $_gpd $prefix] $k]} {
            lassign [dict get [dict get $_gpd $prefix] $k] x y orient plc_name
            place_macro -macro_name [list $odb_name] -location [list $x $y] -orientation $orient
            dict set _matched_group "${prefix}::${k}" 1
            incr _placed
        } else {
            lappend _unmatched_odb "$odb_name (group=$prefix, k=$k)"
        }
        incr k
    }
}

# Pass 3: Report expected entries that were not matched.
foreach plc_name $_direct_expected {
    if {![dict exists $_matched_direct $plc_name]} {
        lappend _unmatched_plc "$plc_name (direct)"
    }
}

dict for {prefix kmap} $_gpd {
    dict for {k pdata} $kmap {
        set key "${prefix}::${k}"
        if {![dict exists $_matched_group $key]} {
            lappend _unmatched_plc "$prefix (k=$k)"
        }
    }
}

puts "Placed $_placed macros (expected 133)"
if {$_placed != 133} {
    puts "WARNING: Expected 133 macros but placed $_placed"
    if {[llength $_unmatched_odb] > 0} {
        puts "Unmatched ODB instances:"
        foreach u $_unmatched_odb { puts "  $u" }
    }
    if {[llength $_unmatched_plc] > 0} {
        puts "Unmatched PLC targets:"
        foreach u $_unmatched_plc { puts "  $u" }
    }
}
