# Macro Placement for OpenROAD-flow-scripts
# Generated by partcl-macro-place-challenge
#
# Runtime matching strategy:
# 1) Direct hierarchical-name matching for explicit .plc macro names
# 2) Group/index matching for macro_mem[K] style names

# Direct placement data
set _dpd [dict create]
set _direct_expected [list]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank0_ram0.rmod.rmod_a} [list 987.299927 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_a} [list 987.299927 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank0_ram0_rmod_rmod_a} [list 987.299927 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank0_ram0.rmod.rmod_b} [list 1113.270020 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_b} [list 1113.270020 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank0_ram0_rmod_rmod_b} [list 1113.270020 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank0_ram1.rmod.rmod_a} [list 1004.400024 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_a} [list 1004.400024 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank0_ram1_rmod_rmod_a} [list 1004.400024 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank0_ram1.rmod.rmod_b} [list 1127.709961 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_b} [list 1127.709961 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank0_ram1_rmod_rmod_b} [list 1127.709961 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank10_ram0.rmod.rmod_a} [list 300.329987 1370.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_a} [list 300.329987 1370.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank10_ram0_rmod_rmod_a} [list 300.329987 1370.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank10_ram0.rmod.rmod_b} [list 176.449997 1370.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_b} [list 176.449997 1370.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank10_ram0_rmod_rmod_b} [list 176.449997 1370.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank10_ram1.rmod.rmod_a} [list 291.589996 1581.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_a} [list 291.589996 1581.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank10_ram1_rmod_rmod_a} [list 291.589996 1581.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank10_ram1.rmod.rmod_b} [list 163.339996 1581.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_b} [list 163.339996 1581.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank10_ram1_rmod_rmod_b} [list 163.339996 1581.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank11_ram0.rmod.rmod_a} [list 415.660004 1662.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_a} [list 415.660004 1662.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank11_ram0_rmod_rmod_a} [list 415.660004 1662.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank11_ram0.rmod.rmod_b} [list 547.069946 1650.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_b} [list 547.069946 1650.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank11_ram0_rmod_rmod_b} [list 547.069946 1650.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank11_ram1.rmod.rmod_a} [list 422.500000 1448.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_a} [list 422.500000 1448.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank11_ram1_rmod_rmod_a} [list 422.500000 1448.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank11_ram1.rmod.rmod_b} [list 550.489990 1440.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_b} [list 550.489990 1440.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank11_ram1_rmod_rmod_b} [list 550.489990 1440.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank12_ram0.rmod.rmod_a} [list 596.729980 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_a} [list 596.729980 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank12_ram0_rmod_rmod_a} [list 596.729980 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank12_ram0.rmod.rmod_b} [list 730.800049 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_b} [list 730.800049 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank12_ram0_rmod_rmod_b} [list 730.800049 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank12_ram1.rmod.rmod_a} [list 631.310059 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_a} [list 631.310059 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank12_ram1_rmod_rmod_a} [list 631.310059 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank12_ram1.rmod.rmod_b} [list 852.020020 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_b} [list 852.020020 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank12_ram1_rmod_rmod_b} [list 852.020020 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank13_ram0.rmod.rmod_a} [list 385.260010 1875.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_a} [list 385.260010 1875.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank13_ram0_rmod_rmod_a} [list 385.260010 1875.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank13_ram0.rmod.rmod_b} [list 512.109985 1865.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_b} [list 512.109985 1865.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank13_ram0_rmod_rmod_b} [list 512.109985 1865.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank13_ram1.rmod.rmod_a} [list 472.019989 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_a} [list 472.019989 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank13_ram1_rmod_rmod_a} [list 472.019989 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank13_ram1.rmod.rmod_b} [list 337.000000 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_b} [list 337.000000 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank13_ram1_rmod_rmod_b} [list 337.000000 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank14_ram0.rmod.rmod_a} [list 675.319946 1650.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_a} [list 675.319946 1650.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank14_ram0_rmod_rmod_a} [list 675.319946 1650.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank14_ram0.rmod.rmod_b} [list 800.339966 1650.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_b} [list 800.339966 1650.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank14_ram0_rmod_rmod_b} [list 800.339966 1650.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank14_ram1.rmod.rmod_a} [list 754.170044 1863.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_a} [list 754.170044 1863.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank14_ram1_rmod_rmod_a} [list 754.170044 1863.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank14_ram1.rmod.rmod_b} [list 875.199951 1847.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_b} [list 875.199951 1847.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank14_ram1_rmod_rmod_b} [list 875.199951 1847.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank15_ram0.rmod.rmod_a} [list 999.459961 1847.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_a} [list 999.459961 1847.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank15_ram0_rmod_rmod_a} [list 999.459961 1847.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank15_ram0.rmod.rmod_b} [list 1121.630005 1858.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_b} [list 1121.630005 1858.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank15_ram0_rmod_rmod_b} [list 1121.630005 1858.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank15_ram1.rmod.rmod_a} [list 1113.459961 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_a} [list 1113.459961 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank15_ram1_rmod_rmod_a} [list 1113.459961 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank15_ram1.rmod.rmod_b} [list 987.109985 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_b} [list 987.109985 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank15_ram1_rmod_rmod_b} [list 987.109985 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank16_ram0.rmod.rmod_a} [list 1670.539917 1398.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_a} [list 1670.539917 1398.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank16_ram0_rmod_rmod_a} [list 1670.539917 1398.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank16_ram0.rmod.rmod_b} [list 1547.039917 1410.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_b} [list 1547.039917 1410.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank16_ram0_rmod_rmod_b} [list 1547.039917 1410.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank16_ram1.rmod.rmod_a} [list 1427.909912 1556.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_a} [list 1427.909912 1556.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank16_ram1_rmod_rmod_a} [list 1427.909912 1556.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank16_ram1.rmod.rmod_b} [list 1421.069946 1350.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_b} [list 1421.069946 1350.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank16_ram1_rmod_rmod_b} [list 1421.069946 1350.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank17_ram0.rmod.rmod_a} [list 1603.089966 1184.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_a} [list 1603.089966 1184.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank17_ram0_rmod_rmod_a} [list 1603.089966 1184.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank17_ram0.rmod.rmod_b} [list 1604.989990 969.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_b} [list 1604.989990 969.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank17_ram0_rmod_rmod_b} [list 1604.989990 969.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank17_ram1.rmod.rmod_a} [list 1728.109985 1184.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_a} [list 1728.109985 1184.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank17_ram1_rmod_rmod_a} [list 1728.109985 1184.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank17_ram1.rmod.rmod_b} [list 1728.489990 969.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_b} [list 1728.489990 969.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank17_ram1_rmod_rmod_b} [list 1728.489990 969.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank18_ram0.rmod.rmod_a} [list 2006.790000 974.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_a} [list 2006.790000 974.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank18_ram0_rmod_rmod_a} [list 2006.790000 974.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank18_ram0.rmod.rmod_b} [list 2006.790000 974.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_b} [list 2006.790000 974.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank18_ram0_rmod_rmod_b} [list 2006.790000 974.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank18_ram1.rmod.rmod_a} [list 1977.579956 1006.279968 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_a} [list 1977.579956 1006.279968 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank18_ram1_rmod_rmod_a} [list 1977.579956 1006.279968 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank18_ram1.rmod.rmod_b} [list 1854.459961 981.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_b} [list 1854.459961 981.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank18_ram1_rmod_rmod_b} [list 1854.459961 981.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank19_ram0.rmod.rmod_a} [list 1483.770020 1066.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_a} [list 1483.770020 1066.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank19_ram0_rmod_rmod_a} [list 1483.770020 1066.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank19_ram0.rmod.rmod_b} [list 1484.719971 859.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_b} [list 1484.719971 859.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank19_ram0_rmod_rmod_b} [list 1484.719971 859.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank19_ram1.rmod.rmod_a} [list 1361.409912 1149.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_a} [list 1361.409912 1149.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank19_ram1_rmod_rmod_a} [list 1361.409912 1149.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank19_ram1.rmod.rmod_b} [list 1358.939941 937.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_b} [list 1358.939941 937.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank19_ram1_rmod_rmod_b} [list 1358.939941 937.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank1_ram0.rmod.rmod_a} [list 623.709961 562.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_a} [list 623.709961 562.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank1_ram0_rmod_rmod_a} [list 623.709961 562.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank1_ram0.rmod.rmod_b} [list 631.500000 349.679993 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_b} [list 631.500000 349.679993 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank1_ram0_rmod_rmod_b} [list 631.500000 349.679993 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank1_ram1.rmod.rmod_a} [list 495.199982 600.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_a} [list 495.199982 600.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank1_ram1_rmod_rmod_a} [list 495.199982 600.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank1_ram1.rmod.rmod_b} [list 502.800018 395.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_b} [list 502.800018 395.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank1_ram1_rmod_rmod_b} [list 502.800018 395.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank20_ram0.rmod.rmod_a} [list 1175.469971 1444.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_a} [list 1175.469971 1444.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank20_ram0_rmod_rmod_a} [list 1175.469971 1444.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank20_ram0.rmod.rmod_b} [list 1301.939941 1450.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_b} [list 1301.939941 1450.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank20_ram0_rmod_rmod_b} [list 1301.939941 1450.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank20_ram1.rmod.rmod_a} [list 1308.780029 1662.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_a} [list 1308.780029 1662.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank20_ram1_rmod_rmod_a} [list 1308.780029 1662.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank20_ram1.rmod.rmod_b} [list 1178.130005 1657.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_b} [list 1178.130005 1657.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank20_ram1_rmod_rmod_b} [list 1178.130005 1657.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank21_ram0.rmod.rmod_a} [list 1371.479980 1877.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_a} [list 1371.479980 1877.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank21_ram0_rmod_rmod_a} [list 1371.479980 1877.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank21_ram0.rmod.rmod_b} [list 1372.809937 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_b} [list 1372.809937 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank21_ram0_rmod_rmod_b} [list 1372.809937 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank21_ram1.rmod.rmod_a} [list 1246.839966 1877.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_a} [list 1246.839966 1877.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank21_ram1_rmod_rmod_a} [list 1246.839966 1877.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank21_ram1.rmod.rmod_b} [list 1246.079956 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_b} [list 1246.079956 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank21_ram1_rmod_rmod_b} [list 1246.079956 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank22_ram0.rmod.rmod_a} [list 1505.619995 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_a} [list 1505.619995 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank22_ram0_rmod_rmod_a} [list 1505.619995 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank22_ram0.rmod.rmod_b} [list 1633.109985 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_b} [list 1633.109985 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank22_ram0_rmod_rmod_b} [list 1633.109985 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank22_ram1.rmod.rmod_a} [list 1738.939941 1835.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_a} [list 1738.939941 1835.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank22_ram1_rmod_rmod_a} [list 1738.939941 1835.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank22_ram1.rmod.rmod_b} [list 1762.309937 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_b} [list 1762.309937 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank22_ram1_rmod_rmod_b} [list 1762.309937 1949.250000 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank23_ram0.rmod.rmod_a} [list 1493.839966 1840.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_a} [list 1493.839966 1840.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank23_ram0_rmod_rmod_a} [list 1493.839966 1840.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank23_ram0.rmod.rmod_b} [list 1615.439941 1835.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_b} [list 1615.439941 1835.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank23_ram0_rmod_rmod_b} [list 1615.439941 1835.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank23_ram1.rmod.rmod_a} [list 1693.530029 1626.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_a} [list 1693.530029 1626.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank23_ram1_rmod_rmod_a} [list 1693.530029 1626.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank23_ram1.rmod.rmod_b} [list 1566.989990 1626.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_b} [list 1566.989990 1626.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank23_ram1_rmod_rmod_b} [list 1566.989990 1626.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank24_ram0.rmod.rmod_a} [list 1245.319946 744.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_a} [list 1245.319946 744.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank24_ram0_rmod_rmod_a} [list 1245.319946 744.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank24_ram0.rmod.rmod_b} [list 1252.729980 527.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_b} [list 1252.729980 527.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank24_ram0_rmod_rmod_b} [list 1252.729980 527.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank24_ram1.rmod.rmod_a} [list 1365.589966 726.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_a} [list 1365.589966 726.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank24_ram1_rmod_rmod_a} [list 1365.589966 726.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank24_ram1.rmod.rmod_b} [list 1379.650024 520.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_b} [list 1379.650024 520.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank24_ram1_rmod_rmod_b} [list 1379.650024 520.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank25_ram0.rmod.rmod_a} [list 1753.189941 747.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_a} [list 1753.189941 747.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank25_ram0_rmod_rmod_a} [list 1753.189941 747.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank25_ram0.rmod.rmod_b} [list 1763.069946 535.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_b} [list 1763.069946 535.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank25_ram0_rmod_rmod_b} [list 1763.069946 535.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank25_ram1.rmod.rmod_a} [list 1617.530029 747.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_a} [list 1617.530029 747.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank25_ram1_rmod_rmod_a} [list 1617.530029 747.280029 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank25_ram1.rmod.rmod_b} [list 1507.969971 541.280029 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_b} [list 1507.969971 541.280029 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank25_ram1_rmod_rmod_b} [list 1507.969971 541.280029 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank26_ram0.rmod.rmod_a} [list 1637.289917 535.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_a} [list 1637.289917 535.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank26_ram0_rmod_rmod_a} [list 1637.289917 535.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank26_ram0.rmod.rmod_b} [list 1651.539917 320.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_b} [list 1651.539917 320.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank26_ram0_rmod_rmod_b} [list 1651.539917 320.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank26_ram1.rmod.rmod_a} [list 1389.030029 310.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_a} [list 1389.030029 310.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank26_ram1_rmod_rmod_a} [list 1389.030029 310.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank26_ram1.rmod.rmod_b} [list 1519.109985 320.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_b} [list 1519.109985 320.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank26_ram1_rmod_rmod_b} [list 1519.109985 320.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank27_ram0.rmod.rmod_a} [list 1897.209961 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_a} [list 1897.209961 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank27_ram0_rmod_rmod_a} [list 1897.209961 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank27_ram0.rmod.rmod_b} [list 2006.790000 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_b} [list 2006.790000 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank27_ram0_rmod_rmod_b} [list 2006.790000 541.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank27_ram1.rmod.rmod_a} [list 1884.099976 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_a} [list 1884.099976 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank27_ram1_rmod_rmod_a} [list 1884.099976 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank27_ram1.rmod.rmod_b} [list 2006.790000 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_b} [list 2006.790000 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank27_ram1_rmod_rmod_b} [list 2006.790000 758.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank28_ram0.rmod.rmod_a} [list 2006.790000 1403.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_a} [list 2006.790000 1403.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank28_ram0_rmod_rmod_a} [list 2006.790000 1403.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank28_ram0.rmod.rmod_b} [list 2006.790000 1403.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_b} [list 2006.790000 1403.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank28_ram0_rmod_rmod_b} [list 2006.790000 1403.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank28_ram1.rmod.rmod_a} [list 2006.790000 1191.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_a} [list 2006.790000 1191.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank28_ram1_rmod_rmod_a} [list 2006.790000 1191.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank28_ram1.rmod.rmod_b} [list 2006.790000 1191.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_b} [list 2006.790000 1191.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank28_ram1_rmod_rmod_b} [list 2006.790000 1191.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank29_ram0.rmod.rmod_a} [list 1969.409912 1657.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_a} [list 1969.409912 1657.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank29_ram0_rmod_rmod_a} [list 1969.409912 1657.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank29_ram0.rmod.rmod_b} [list 1981.949951 1874.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_b} [list 1981.949951 1874.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank29_ram0_rmod_rmod_b} [list 1981.949951 1874.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank29_ram1.rmod.rmod_a} [list 1835.079956 1641.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_a} [list 1835.079956 1641.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank29_ram1_rmod_rmod_a} [list 1835.079956 1641.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank29_ram1.rmod.rmod_b} [list 1859.589966 1858.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_b} [list 1859.589966 1858.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank29_ram1_rmod_rmod_b} [list 1859.589966 1858.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank2_ram0.rmod.rmod_a} [list 767.280029 349.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_a} [list 767.280029 349.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank2_ram0_rmod_rmod_a} [list 767.280029 349.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank2_ram0.rmod.rmod_b} [list 893.819946 349.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_b} [list 893.819946 349.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank2_ram0_rmod_rmod_b} [list 893.819946 349.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank2_ram1.rmod.rmod_a} [list 753.790039 570.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_a} [list 753.790039 570.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank2_ram1_rmod_rmod_a} [list 753.790039 570.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank2_ram1.rmod.rmod_b} [list 878.239990 563.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_b} [list 878.239990 563.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank2_ram1_rmod_rmod_b} [list 878.239990 563.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank30_ram0.rmod.rmod_a} [list 2006.790000 1618.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_a} [list 2006.790000 1618.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank30_ram0_rmod_rmod_a} [list 2006.790000 1618.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank30_ram0.rmod.rmod_b} [list 2006.790000 1618.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_b} [list 2006.790000 1618.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank30_ram0_rmod_rmod_b} [list 2006.790000 1618.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank30_ram1.rmod.rmod_a} [list 2006.790000 1832.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_a} [list 2006.790000 1832.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank30_ram1_rmod_rmod_a} [list 2006.790000 1832.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank30_ram1.rmod.rmod_b} [list 2006.790000 1832.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_b} [list 2006.790000 1832.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank30_ram1_rmod_rmod_b} [list 2006.790000 1832.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank31_ram0.rmod.rmod_a} [list 1851.679932 1203.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_a} [list 1851.679932 1203.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank31_ram0_rmod_rmod_a} [list 1851.679932 1203.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank31_ram0.rmod.rmod_b} [list 1977.199951 1223.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_b} [list 1977.199951 1223.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank31_ram0_rmod_rmod_b} [list 1977.199951 1223.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank31_ram1.rmod.rmod_a} [list 1795.439941 1410.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_a} [list 1795.439941 1410.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank31_ram1_rmod_rmod_a} [list 1795.439941 1410.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank31_ram1.rmod.rmod_b} [list 1975.299927 1440.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_b} [list 1975.299927 1440.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank31_ram1_rmod_rmod_b} [list 1975.299927 1440.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank3_ram0.rmod.rmod_a} [list 733.459961 895.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_a} [list 733.459961 895.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank3_ram0_rmod_rmod_a} [list 733.459961 895.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank3_ram0.rmod.rmod_b} [list 852.589966 773.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_b} [list 852.589966 773.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank3_ram0_rmod_rmod_b} [list 852.589966 773.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank3_ram1.rmod.rmod_a} [list 610.719971 986.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_a} [list 610.719971 986.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank3_ram1_rmod_rmod_a} [list 610.719971 986.679993 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank3_ram1.rmod.rmod_b} [list 598.180054 778.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_b} [list 598.180054 778.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank3_ram1_rmod_rmod_b} [list 598.180054 778.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank4_ram0.rmod.rmod_a} [list 863.609985 1189.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_a} [list 863.609985 1189.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank4_ram0_rmod_rmod_a} [list 863.609985 1189.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank4_ram0.rmod.rmod_b} [list 857.339966 985.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_b} [list 857.339966 985.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank4_ram0_rmod_rmod_b} [list 857.339966 985.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank4_ram1.rmod.rmod_a} [list 989.199951 1189.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_a} [list 989.199951 1189.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank4_ram1_rmod_rmod_a} [list 989.199951 1189.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank4_ram1.rmod.rmod_b} [list 982.739990 979.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_b} [list 982.739990 979.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank4_ram1_rmod_rmod_b} [list 982.739990 979.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank5_ram0.rmod.rmod_a} [list 1240.760010 1234.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_a} [list 1240.760010 1234.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank5_ram0_rmod_rmod_a} [list 1240.760010 1234.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank5_ram0.rmod.rmod_b} [list 1107.949951 993.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_b} [list 1107.949951 993.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank5_ram0_rmod_rmod_b} [list 1107.949951 993.480042 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank5_ram1.rmod.rmod_a} [list 1118.209961 1205.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_a} [list 1118.209961 1205.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank5_ram1_rmod_rmod_a} [list 1118.209961 1205.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank5_ram1.rmod.rmod_b} [list 1233.159912 1013.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_b} [list 1233.159912 1013.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank5_ram1_rmod_rmod_b} [list 1233.159912 1013.080017 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank6_ram0.rmod.rmod_a} [list 926.880005 1406.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_a} [list 926.880005 1406.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank6_ram0_rmod_rmod_a} [list 926.880005 1406.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank6_ram0.rmod.rmod_b} [list 1050.760010 1406.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_b} [list 1050.760010 1406.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank6_ram0_rmod_rmod_b} [list 1050.760010 1406.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank6_ram1.rmod.rmod_a} [list 926.500000 1620.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_a} [list 926.500000 1620.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank6_ram1_rmod_rmod_a} [list 926.500000 1620.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank6_ram1.rmod.rmod_b} [list 1052.089966 1620.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_b} [list 1052.089966 1620.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank6_ram1_rmod_rmod_b} [list 1052.089966 1620.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank7_ram0.rmod.rmod_a} [list 800.910034 1438.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_a} [list 800.910034 1438.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank7_ram0_rmod_rmod_a} [list 800.910034 1438.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank7_ram0.rmod.rmod_b} [list 674.630005 1427.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_b} [list 674.630005 1427.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank7_ram0_rmod_rmod_b} [list 674.630005 1427.679932 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank7_ram1.rmod.rmod_a} [list 615.920044 1204.880005 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_a} [list 615.920044 1204.880005 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank7_ram1_rmod_rmod_a} [list 615.920044 1204.880005 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank7_ram1.rmod.rmod_b} [list 738.209961 1118.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_b} [list 738.209961 1118.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank7_ram1_rmod_rmod_b} [list 738.209961 1118.079956 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank8_ram0.rmod.rmod_a} [list 360.369995 1165.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_a} [list 360.369995 1165.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank8_ram0_rmod_rmod_a} [list 360.369995 1165.880005 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank8_ram0.rmod.rmod_b} [list 361.700012 955.679993 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_b} [list 361.700012 955.679993 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank8_ram0_rmod_rmod_b} [list 361.700012 955.679993 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank8_ram1.rmod.rmod_a} [list 487.290009 1171.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_a} [list 487.290009 1171.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank8_ram1_rmod_rmod_a} [list 487.290009 1171.479980 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank8_ram1.rmod.rmod_b} [list 485.959991 955.679993 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_b} [list 485.959991 955.679993 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank8_ram1_rmod_rmod_b} [list 485.959991 955.679993 S {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank9_ram0.rmod.rmod_a} [list 34.330002 1587.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_a} [list 34.330002 1587.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank9_ram0_rmod_rmod_a} [list 34.330002 1587.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank9_ram0.rmod.rmod_b} [list 17.800003 1797.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_b} [list 17.800003 1797.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank9_ram0_rmod_rmod_b} [list 17.800003 1797.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/rmod/rmod_b}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_a}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank9_ram1.rmod.rmod_a} [list 141.869995 1797.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_a} [list 141.869995 1797.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_a}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank9_ram1_rmod_rmod_a} [list 141.869995 1797.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_a}]
lappend _direct_expected {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_b}
dict set _dpd {u_NV_NVDLA_cbuf.u_cbuf_ram_bank9_ram1.rmod.rmod_b} [list 265.559998 1797.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_b} [list 265.559998 1797.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_b}]
dict set _dpd {u_NV_NVDLA_cbuf_u_cbuf_ram_bank9_ram1_rmod_rmod_b} [list 265.559998 1797.279907 N {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/rmod/rmod_b}]

# Placement data: group_prefix -> flat_index -> {x y orient plc_name}
set _gpd [dict create]

# Pass 1: Scan all block instances.
# - Apply direct-name placements first.
# - Collect genblk-style names for group/index matching.
set _odb_groups [dict create]
set _matched_direct [dict create]
set _matched_group [dict create]
set _placed 0
set _unmatched_odb [list]
set _unmatched_plc [list]

set block [ord::get_db_block]
foreach inst [$block getInsts] {
    if {![$inst isBlock]} {
        continue
    }

    set name [$inst getName]

    if {[dict exists $_dpd $name]} {
        lassign [dict get $_dpd $name] x y orient plc_name
        place_macro -macro_name [list $name] -location [list $x $y] -orientation $orient
        dict set _matched_direct $plc_name 1
        incr _placed
        continue
    }

    if {[regexp {^(.+)\.genblk1_(\d+)__i_ram\.macro_mem_(\d+)$} $name -> prefix genblk_idx mem_idx]} {
        dict lappend _odb_groups $prefix [list $genblk_idx $mem_idx $name]
        continue
    }

    lappend _unmatched_odb $name
}

# Pass 2: For each group, sort by (genblk_idx, mem_idx) to get linear ordering,
# then match to our .plc flat indices.
dict for {prefix entries} $_odb_groups {
    # Sort entries by genblk_idx then mem_idx (both numeric)
    set sorted_entries [lsort -command {apply {{a b} {
        lassign $a ga ma
        lassign $b gb mb
        set ga [expr {int($ga)}]; set ma [expr {int($ma)}]
        set gb [expr {int($gb)}]; set mb [expr {int($mb)}]
        if {$ga != $gb} { return [expr {$ga - $gb}] }
        return [expr {$ma - $mb}]
    }}} $entries]

    # Assign linear index K=0,1,2,...
    set k 0
    foreach entry $sorted_entries {
        lassign $entry genblk_idx mem_idx odb_name
        if {[dict exists $_gpd $prefix] && [dict exists [dict get $_gpd $prefix] $k]} {
            lassign [dict get [dict get $_gpd $prefix] $k] x y orient plc_name
            place_macro -macro_name [list $odb_name] -location [list $x $y] -orientation $orient
            dict set _matched_group "${prefix}::${k}" 1
            incr _placed
        } else {
            lappend _unmatched_odb "$odb_name (group=$prefix, k=$k)"
        }
        incr k
    }
}

# Pass 3: Report expected entries that were not matched.
foreach plc_name $_direct_expected {
    if {![dict exists $_matched_direct $plc_name]} {
        lappend _unmatched_plc "$plc_name (direct)"
    }
}

dict for {prefix kmap} $_gpd {
    dict for {k pdata} $kmap {
        set key "${prefix}::${k}"
        if {![dict exists $_matched_group $key]} {
            lappend _unmatched_plc "$prefix (k=$k)"
        }
    }
}

puts "Placed $_placed macros (expected 128)"
if {$_placed != 128} {
    puts "WARNING: Expected 128 macros but placed $_placed"
    if {[llength $_unmatched_odb] > 0} {
        puts "Unmatched ODB instances:"
        foreach u $_unmatched_odb { puts "  $u" }
    }
    if {[llength $_unmatched_plc] > 0} {
        puts "Unmatched PLC targets:"
        foreach u $_unmatched_plc { puts "  $u" }
    }
}
